# Generated by Django 5.2.4 on 2025-08-09 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_list_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(related_name='houses', through='core.HouseUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house'),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
