# Generated by Django 5.2.4 on 2025-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_house_options_remove_house_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergencial'), ('MONTHLY', 'Mensal')], default='MONTHLY', max_length=10),
        ),
    ]
